### ISSUE TITLE
Ubuntu extra release 

### ISSUE THREAD

**Issue by DavidAKopriva** [trixi-framework/FTObjectLibrary#7]
An issue seems to have arisen between PR#3 and PR#4. The ubuntu version is now giving a "attempt to release .." warning that wasn't there in #3 or earlier but is in #4 and later. The only difference in the code is in the comments that were changed for the FORD documentation. The Mac and Windows versions are unchanged and do not report this error.

**Comment by DavidAKopriva** [comment]
That issue seems to have gone away since PR #5  and has not reappeared up through PR #10

**Comment by sloede** [comment]
I believe this issue can be closed. Do you agree @DavidAKopriva ?

**Comment by DavidAKopriva** [comment]
Yes, I agree. Very strange, but it hasn't shown up in a while, and never has shown up on the other two systems.
